# Generated by Django 2.2 on 2019-04-16 12:58

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name of the plan')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_range', django.contrib.postgres.fields.ranges.DateRangeField(verbose_name='Time range')),
                ('is_active', models.BooleanField(default=False, verbose_name='Set as active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Date of training')),
                ('training_main', models.CharField(max_length=32, verbose_name='Main training')),
                ('distance_main', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Distance [km]')),
                ('time_main', models.SmallIntegerField(verbose_name='Time [min]')),
                ('training_additional', models.CharField(blank=True, max_length=32, null=True, verbose_name='Additional training (optional)')),
                ('distance_additional', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Distance [km]')),
                ('time_additional', models.SmallIntegerField(verbose_name='Time [min]')),
                ('accomplished', models.BooleanField(default=False)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RunScheduleApp.WorkoutPlan', unique_for_date=models.DateField(verbose_name='Date of training'), verbose_name='Add training to workout plan')),
            ],
        ),
    ]
