# Generated by Django 2.2 on 2019-04-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RunScheduleApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='distance_additional',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Distance [km]'),
        ),
        migrations.AlterField(
            model_name='training',
            name='time_additional',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Time [min]'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Set as current'),
        ),
    ]
