# Generated by Django 2.1.4 on 2018-12-18 07:24

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RunScheduleApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytraining',
            name='additional',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dailytraining',
            name='additional_quantity',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='date_range',
            field=django.contrib.postgres.fields.ranges.DateRangeField(verbose_name='Termin'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='description',
            field=models.TextField(null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Ustaw jako bieżący'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='plan_name',
            field=models.CharField(max_length=64, verbose_name='Nazwa planu'),
        ),
    ]
