# Generated by Django 2.1.4 on 2018-12-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RunScheduleApp', '0002_auto_20181218_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytraining',
            name='additional',
            field=models.CharField(max_length=32, null=True, verbose_name='Dodatkowy trening'),
        ),
        migrations.AlterField(
            model_name='dailytraining',
            name='additional_quantity',
            field=models.CharField(max_length=32, null=True, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='dailytraining',
            name='day',
            field=models.DateField(verbose_name='Wybierz datę'),
        ),
        migrations.AlterField(
            model_name='dailytraining',
            name='description',
            field=models.TextField(null=True, verbose_name='Dodatkowy opis'),
        ),
        migrations.AlterField(
            model_name='dailytraining',
            name='training_distance',
            field=models.SmallIntegerField(verbose_name='Dystans (km)'),
        ),
        migrations.AlterField(
            model_name='dailytraining',
            name='training_type',
            field=models.CharField(max_length=32, verbose_name='Rodzaj treningu'),
        ),
        migrations.AlterField(
            model_name='dailytraining',
            name='workout_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RunScheduleApp.WorkoutPlan', unique_for_date='day', verbose_name='Dodaj trening do planu'),
        ),
    ]
