# Generated by Django 2.2 on 2019-05-08 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RunScheduleApp', '0003_auto_20190417_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_info', models.CharField(max_length=128)),
                ('training_distance', models.DecimalField(decimal_places=1, max_digits=3)),
                ('training_time', models.SmallIntegerField()),
                ('comments', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
