# Generated by Django 2.1.4 on 2018-12-18 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RunScheduleApp', '0003_auto_20181218_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytraining',
            name='additional',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Dodatkowy trening'),
        ),
        migrations.AlterField(
            model_name='dailytraining',
            name='additional_quantity',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='dailytraining',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Dodatkowy opis'),
        ),
        migrations.AlterField(
            model_name='dailytraining',
            name='workout_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RunScheduleApp.WorkoutPlan', unique_for_date=models.DateField(verbose_name='Wybierz datę'), verbose_name='Dodaj trening do planu'),
        ),
    ]
