# Generated by Django 2.1.4 on 2018-12-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RunScheduleApp', '0004_auto_20181218_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytraining',
            name='additional',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Dodatkowo'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
    ]
