# Generated by Django 2.2 on 2019-05-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RunScheduleApp', '0006_trainingdiary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdiary',
            name='comments',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Comments'),
        ),
    ]
